fix: saving blocks with a one-item tuple
The latest line of blocks would be aninteger followed by a comma, and as the latest item of the list, it's forbidden in JSON.
Therefore, it would end on:

    json.decoder.JSONDecodeError: Expecting value: line X column Y (char Z)